### PR TITLE
New travis infrastructure

### PR DESCRIPTION
**Pull request by cameleeck**

### CODE REVIEW

**Comment by cameleeck** [comment]
@marcingrzejszczak @szpak @nurkiewicz @dst - please check if everything is ok

**Comment by cameleeck** [comment]
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by marcingrzejszczak** [comment]
+1

**Comment by dst** [comment]
+1

**Pull request merged**
