### PR TITLE
Feature/latest gradle

### PR DESCRIPTION
**Pull request by mariuszs**
this works with

```
microInfraSpringVersion=2.0.26-SNAPSHOT
```

### CODE REVIEW

**Comment by szpak** [comment]
@mariuszs Is there everything working on your machine?

```
com.ofg.twitter.geb.springcloud.SpringCloudHealthEndpointUISpec > Open health page FAILED

    java.lang.IllegalStateException: Failed to load ApplicationContext

        Caused by:

        org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchStubRunner' defined in com.ofg.stub.config.StubRunnerConfiguration: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo(Ljava/lang/String;)Lcom/github/tomakehurst/wiremock/client/UrlMatchingStrategy;

            Caused by:

            java.lang.NoSuchMethodError: com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo(Ljava/lang/String;)Lcom/github/tomakehurst/wiremock/client/UrlMatchingStrategy;
```

**Comment by szpak** [comment]
I missed your comment...

**Comment by mariuszs** [comment]
This is very strange,that we need to explicity specify wiremock here (it is specified in microinfra)

**Comment by mariuszs** [comment]
this is closed, because some problems with spring boot 1.4  (we need to update spring cloud too)

**Pull request closed without merging**
