### PR TITLE
[#45] Removing bower grunt nodejs

### PR DESCRIPTION
**Pull request by marcingrzejszczak**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@szimano - any comments to that? :P

**Comment by marcingrzejszczak** [comment]
yes :) everything that was in *build.gradle* was removed and everything that was downloaded / copied from this *dist* folder to *static* was moved to *static*.

**Comment by szimano** [comment]
well then if you want to throw away all the grunt goodies (livereload, javascript minimisation, javascript code analysis etc. etc.) then there's no point in copying whole bower/** folders. just the javascript files will be enough

**Comment by marcingrzejszczak** [comment]
@wybczu - We've decided that for the hackathon purposes we're going to use this branch but @szimano will take a look at all those karma/grunt/yeoman/bower issues

**Comment by marcingrzejszczak** [comment]
@szimano - when will you fix it? :P

**Comment by szimano** [comment]
3rd quarter

**Pull request closed without merging**
